export const MOVIE = [
    { 
      id: 'g1',
      title: 'Star War',
      genre: 'Action', 
      country: 'USA',
      img: 'https://media.timeout.com/images/105863223/image.jpg',
    },
    { 
      id: 'g2',
      title: 'Spider-Man',
      genre: 'Drama',
      country: 'ASIA',
      img: 'https://assetsio.reedpopcdn.com/Spider-Banner_AVVWjOb.jpg?width=1200&height=630&fit=crop&enable=upscale&auto=webp',
   },
    { 
      id: 'g3', 
      title: 'Avengers',
      genre: 'Comedy',
      country: 'EUROPE',
      img: 'https://cdn.britannica.com/60/182360-050-CD8878D6/Avengers-Age-of-Ultron-Joss-Whedon.jpg',
    },
    { 
      id: 'g4', 
      title: 'Oppenheimer',
      genre: 'Action',
      country: 'EUROPE',
      img: 'https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_.jpg',
    },
    { 
      id: 'g5', 
      title: 'Barbie',
      genre: 'Comedy',
      country: 'USA',
      img: 'https://www.barbie-themovie.com/images/gallery/img1.jpg',
    },
    { 
      id: 'g6', 
      title: 'Dracula',
      genre: 'Action',
      country: 'ASIA',
      img: 'https://m.media-amazon.com/images/M/MV5BMTkwMjIxNTE1OF5BMl5BanBnXkFtZTgwMzM4ODUwNjE@._V1_.jpg',
    },
    { 
      id: 'g7', 
      title: 'Rush',
      genre: 'Comedy',
      country: 'ASIA',
      img: 'https://flxt.tmsimg.com/assets/p21702_p_v10_ab.jpg',
    },
    { 
      id: 'g8', 
      title: 'Iron-Man 2',
      genre: 'Action',
      country: 'USA',
      img: 'https://qph.cf2.quoracdn.net/main-qimg-95f074c06f0ae7e550329f3a298e3244-lq',
    },
    { 
      id: 'g9', 
      title: 'Emily-In-Paris',
      genre: 'Drama',
      country: 'EUROPE',
      img: 'https://static.toiimg.com/photo/msid-78254584/78254584.jpg?76271',
    },
    { 
      id: 'g10', 
      title: 'Lust Stories 2',
      genre: 'Drama',
      country: 'ASIA',
      img: 'https://moviesda4.net/uploads/posters/lust-stories-2-2023.jpg',
    },
  ];